### ISSUE TITLE
how to change index text color?

### ISSUE THREAD

**Issue by ex-git** [kfiri/indexed-section-list#1]
so far this is the best section list I found for RN. 
My app need dark theme and the default index text color is not changeable. Can you add a props to make customs index text possible? I would like to add border and radius to individual index or background.
Thank you.

**Comment by kfiri** [comment]
Thanks for the feedback!
Sorry for the delay, my PC died recently and  I haven't installed everything on my new one yet. I will push the fix for it in the 48 hours, or if you want to, feel free to open a pull request and I'll get to it today

**Comment by ex-git** [comment]
> Thanks for the feedback!
> Sorry for the delay, my PC died recently and I haven't installed everything on my new one yet. I will push the fix for it in the 48 hours, or if you want to, feel free to open a pull request and I'll get to it today

OK. Here is the pr [https://github.com/kfiri/indexed-section-list/pull/2](https://github.com/kfiri/indexed-section-list/pull/2)

**Comment by kfiri** [comment]
Thanks for the pull request! I installed all of the environment I needed and I'm reviewing it now

**Comment by kfiri** [comment]
#2 has been merged :)

Say, Do you think that I should make the `renderItem` prop required and not optional? I think that the default value of it is pretty useless...

**Comment by ex-git** [comment]
> #2 has been merged :)
> 
> Say, Do you think that I should make the `renderItem` prop required and not optional? I think that the default value of it is pretty useless...

thanks.
I agree with you. Default props of renderItem is kind of useless.
Keep up the good work 👍
