### ISSUE TITLE
how to remove line divider in header?

### ISSUE THREAD

**Issue by ddikodroid** [kfiri/indexed-section-list#3]
as the title said, or at least change the style of header text and divider

**Comment by kfiri** [comment]
if you are looking to change the way the section headers look, the `renderSectionHeader` prop is your friend :)
https://reactnative.dev/docs/sectionlist#rendersectionheader

The code for a `SectionHeader` is rather simple, you can see the default value for it in this package here: https://github.com/kfiri/indexed-section-list/blob/master/src/SectionHeader.tsx.

The reason I didn't add more props to change the style of the default section header is that I believe it would give this package a more rigid mindset for the way this package is used (writing your own `SectionHeader` allow you much more flexibility in your project)

**Comment by kfiri** [comment]
@ddikodroid Did that answer your question?

**Comment by ddikodroid** [comment]
Thank you. I forked your package and change it manually.😂

EDIT:
One more question, if i set scrollOnSelect={false} how to make it scroll to Index when I press the index? I know I have to use onSelectIndex props, but idk what kind of function should I pass to this props

**Comment by kfiri** [comment]
> Thank you. I forked your package and change it manually.😂
> 
> EDIT:
> One more question, if i set scrollOnSelect={false} how to make it scroll to Index when I press the index? I know I have to use onSelectIndex props, but idk what kind of function should I pass to this props

Sorry! I didn't see the edit, I will get back to you once I'll get home today
